[package]
name = "modification_updater"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"
chrono = "0.4"
sha2 = "0.10.2"
hex-literal = "0.3.4"
hex_fmt = "0.3.0"
itertools = "0.10.3"

[dev-dependencies]
rstest = "0.13.0"
